services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: canchas_app
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
